export const categories = [
  {
    id: 'disney',
    label: 'Disney Rides',
    title: 'Greatest Disney Ride',
    subtitle: 'Walt Disney World, Orlando',
    emoji: '🏰',
    contestants: [
      { id: 'd1', name: 'Avatar: Flight of Passage', sub: 'Animal Kingdom', emoji: '🌿' },
      { id: 'd2', name: 'Rise of the Resistance', sub: 'Hollywood Studios', emoji: '⚡' },
      { id: 'd3', name: 'Haunted Mansion', sub: 'Magic Kingdom', emoji: '👻' },
      { id: 'd4', name: 'Space Mountain', sub: 'Magic Kingdom', emoji: '🚀' },
      { id: 'd5', name: 'Pirates of the Caribbean', sub: 'Magic Kingdom', emoji: '☠️' },
      { id: 'd6', name: 'Tower of Terror', sub: 'Hollywood Studios', emoji: '🏨' },
      { id: 'd7', name: 'Expedition Everest', sub: 'Animal Kingdom', emoji: '🏔️' },
      { id: 'd8', name: "Tiana's Bayou Adventure", sub: 'Magic Kingdom', emoji: '🐸' },
      { id: 'd9', name: 'Big Thunder Mountain', sub: 'Magic Kingdom', emoji: '🤠' },
      { id: 'd10', name: 'Seven Dwarfs Mine Train', sub: 'Magic Kingdom', emoji: '⛏️' },
      { id: 'd11', name: 'Tron Lightcycle Run', sub: 'Magic Kingdom', emoji: '🔵' },
      { id: 'd12', name: 'Guardians of the Galaxy', sub: 'EPCOT', emoji: '🌌' },
      { id: 'd13', name: "Remy's Ratatouille Adventure", sub: 'EPCOT', emoji: '🐭' },
      { id: 'd14', name: 'Frozen Ever After', sub: 'EPCOT', emoji: '❄️' },
      { id: 'd15', name: 'Test Track', sub: 'EPCOT', emoji: '🏎️' },
      { id: 'd16', name: "Soarin' Around the World", sub: 'EPCOT', emoji: '🌍' },
      { id: 'd17', name: 'Mission: Space', sub: 'EPCOT', emoji: '🛸' },
      { id: 'd18', name: 'Spaceship Earth', sub: 'EPCOT', emoji: '🌐' },
      { id: 'd19', name: 'Kilimanjaro Safaris', sub: 'Animal Kingdom', emoji: '🦁' },
      { id: 'd20', name: 'DINOSAUR', sub: 'Animal Kingdom', emoji: '🦕' },
      { id: 'd21', name: "Na'vi River Journey", sub: 'Animal Kingdom', emoji: '🌺' },
      { id: 'd22', name: 'Kali River Rapids', sub: 'Animal Kingdom', emoji: '🌊' },
      { id: 'd23', name: 'Slinky Dog Dash', sub: 'Hollywood Studios', emoji: '🐕' },
      { id: 'd24', name: 'Millennium Falcon: Smugglers Run', sub: 'Hollywood Studios', emoji: '🚀' },
      { id: 'd25', name: "Rock 'n' Roller Coaster", sub: 'Hollywood Studios', emoji: '🎸' },
      { id: 'd26', name: "Mickey & Minnie's Runaway Railway", sub: 'Hollywood Studios', emoji: '🐭' },
      { id: 'd27', name: 'Toy Story Mania', sub: 'Hollywood Studios', emoji: '🎯' },
      { id: 'd28', name: 'Star Tours', sub: 'Hollywood Studios', emoji: '⭐' },
      { id: 'd29', name: "Muppet*Vision 3D", sub: 'Hollywood Studios', emoji: '🐸' },
      { id: 'd30', name: 'Liberty Square Riverboat', sub: 'Magic Kingdom', emoji: '⛵' },
      { id: 'd31', name: 'Dumbo the Flying Elephant', sub: 'Magic Kingdom', emoji: '🐘' },
      { id: 'd32', name: "Peter Pan's Flight", sub: 'Magic Kingdom', emoji: '🧚' },
      { id: 'd33', name: "It's a Small World", sub: 'Magic Kingdom', emoji: '🌏' },
      { id: 'd34', name: 'The Barnstormer', sub: 'Magic Kingdom', emoji: '✈️' },
      { id: 'd35', name: 'Tomorrowland Speedway', sub: 'Magic Kingdom', emoji: '🏁' },
      { id: 'd36', name: "Buzz Lightyear's Space Ranger Spin", sub: 'Magic Kingdom', emoji: '🤖' },
      { id: 'd37', name: 'Under the Sea - Journey of the Little Mermaid', sub: 'Magic Kingdom', emoji: '🧜' },
      { id: 'd38', name: 'The Magic Carpets of Aladdin', sub: 'Magic Kingdom', emoji: '🪄' },
      { id: 'd39', name: 'Jungle Cruise', sub: 'Magic Kingdom', emoji: '🐊' },
      { id: 'd40', name: 'Walt Disney World Railroad', sub: 'Magic Kingdom', emoji: '🚂' },
      { id: 'd41', name: 'Journey Into Imagination with Figment', sub: 'EPCOT', emoji: '🎨' },
      { id: 'd42', name: 'Living with the Land', sub: 'EPCOT', emoji: '🌱' },
      { id: 'd43', name: 'Prince Charming Regal Carrousel', sub: 'Magic Kingdom', emoji: '🎠' },
      { id: 'd44', name: 'Indiana Jones Epic Stunt Spectacular', sub: 'Hollywood Studios', emoji: '🎬' },
    ]
  },
  {
    id: 'rappers',
    label: 'Rappers',
    title: 'Greatest Rapper',
    subtitle: 'Of All Time',
    emoji: '🎤',
    contestants: [
      { id: 'r1', name: 'Tupac Shakur', sub: 'Death Row Records', emoji: '👑' },
      { id: 'r2', name: 'Biggie Smalls', sub: 'Bad Boy Records', emoji: '🎤' },
      { id: 'r3', name: 'Jay-Z', sub: 'Roc-A-Fella Records', emoji: '💎' },
      { id: 'r4', name: 'Eminem', sub: 'Aftermath Entertainment', emoji: '🎵' },
      { id: 'r5', name: 'Kendrick Lamar', sub: 'pgLang / TDE', emoji: '🏆' },
      { id: 'r6', name: 'Nas', sub: 'Columbia Records', emoji: '🔥' },
      { id: 'r7', name: 'Lil Wayne', sub: 'Cash Money Records', emoji: '🐉' },
      { id: 'r8', name: 'Drake', sub: 'OVO Sound', emoji: '🦉' },
      { id: 'r9', name: 'Rakim', sub: 'Eric B. & Rakim', emoji: '🎙️' },
      { id: 'r10', name: 'Andre 3000', sub: 'OutKast', emoji: '🪐' },
      { id: 'r11', name: 'Ice Cube', sub: 'NWA / Solo', emoji: '🧊' },
      { id: 'r12', name: 'Snoop Dogg', sub: 'Death Row / Doggystyle', emoji: '🐕' },
      { id: 'r13', name: 'DMX', sub: 'Ruff Ryders', emoji: '🐺' },
      { id: 'r14', name: 'Method Man', sub: 'Wu-Tang Clan', emoji: '💨' },
      { id: 'r15', name: 'Big Pun', sub: 'Terror Squad', emoji: '🇵🇷' },
      { id: 'r16', name: 'Common', sub: 'GOOD Music', emoji: '🌻' },
      { id: 'r17', name: 'J. Cole', sub: 'Dreamville', emoji: '🌲' },
      { id: 'r18', name: 'Lauryn Hill', sub: 'Fugees / Solo', emoji: '🌸' },
      { id: 'r19', name: 'LL Cool J', sub: 'Def Jam Records', emoji: '🎧' },
      { id: 'r20', name: 'Big L', sub: "Diggin' in the Crates", emoji: '🪙' },
      { id: 'r21', name: 'Ghostface Killah', sub: 'Wu-Tang Clan', emoji: '👻' },
      { id: 'r22', name: 'GZA', sub: 'Wu-Tang Clan', emoji: '🧠' },
      { id: 'r23', name: 'Scarface', sub: 'Geto Boys', emoji: '🌹' },
      { id: 'r24', name: 'Missy Elliott', sub: 'The Goldmind Inc.', emoji: '🌀' },
      { id: 'r25', name: 'Tech N9ne', sub: 'Strange Music', emoji: '⚡' },
      { id: 'r26', name: 'Busta Rhymes', sub: 'Flipmode Squad', emoji: '🌪️' },
      { id: 'r27', name: 'T.I.', sub: 'Grand Hustle', emoji: '👔' },
      { id: 'r28', name: 'Ludacris', sub: 'Disturbing tha Peace', emoji: '🎲' },
      { id: 'r29', name: 'Kanye West', sub: 'GOOD Music', emoji: '🎨' },
      { id: 'r30', name: 'Rick Ross', sub: 'Maybach Music', emoji: '🐘' },
      { id: 'r31', name: 'Lil Kim', sub: 'Junior M.A.F.I.A.', emoji: '💅' },
      { id: 'r32', name: 'Queen Latifah', sub: 'Flavor Unit', emoji: '👸' },
      { id: 'r33', name: 'Redman', sub: 'Def Squad', emoji: '🌿' },
      { id: 'r34', name: 'Jadakiss', sub: 'The LOX', emoji: '😤' },
      { id: 'r35', name: 'Fat Joe', sub: 'Terror Squad', emoji: '🍀' },
      { id: 'r36', name: "Cam'ron", sub: 'Diplomat Records', emoji: '🩷' },
      { id: 'r37', name: 'Fabolous', sub: 'Desert Storm Records', emoji: '✨' },
      { id: 'r38', name: 'Young Jeezy', sub: 'CTE World', emoji: '❄️' },
      { id: 'r39', name: 'Gucci Mane', sub: '1017 Records', emoji: '🧊' },
      { id: 'r40', name: 'Wiz Khalifa', sub: 'Taylor Gang', emoji: '🌿' },
      { id: 'r41', name: 'Kid Cudi', sub: 'GOOD Music', emoji: '🌙' },
      { id: 'r42', name: 'A$AP Rocky', sub: 'ASAP Mob', emoji: '🌹' },
      { id: 'r43', name: 'Tyler the Creator', sub: 'Odd Future', emoji: '🌺' },
      { id: 'r44', name: 'Logic', sub: 'Visionary Music Group', emoji: '🧬' },
      { id: 'r45', name: 'Big Sean', sub: 'GOOD Music', emoji: '🦁' },
      { id: 'r46', name: 'Meek Mill', sub: 'Maybach Music', emoji: '🦅' },
      { id: 'r47', name: 'Future', sub: 'Freebandz', emoji: '🚀' },
      { id: 'r48', name: '21 Savage', sub: 'Slaughter Gang', emoji: '🔪' },
      { id: 'r50', name: 'Styles P', sub: 'The LOX', emoji: '🗡️' },
      { id: 'r51', name: 'KRS-One', sub: 'Boogie Down Productions', emoji: '📚' },
      { id: 'r52', name: 'Chuck D', sub: 'Public Enemy', emoji: '✊' },
      { id: 'r53', name: 'Slick Rick', sub: 'Def Jam Records', emoji: '👑' },
      { id: 'r54', name: 'Grandmaster Melle Mel', sub: 'Furious Five', emoji: '⚡' },
      { id: 'r55', name: 'Big Daddy Kane', sub: 'Cold Chillin Records', emoji: '🎩' },
      { id: 'r56', name: 'Kool G Rap', sub: 'Cold Chillin Records', emoji: '🔥' },
      { id: 'r57', name: 'Doug E. Fresh', sub: 'Reality Records', emoji: '🎵' },
      { id: 'r58', name: 'MC Lyte', sub: 'First Priority Music', emoji: '🌟' },
      { id: 'r59', name: 'Run', sub: 'Run-DMC', emoji: '🎩' },
      { id: 'r60', name: 'DMC', sub: 'Run-DMC', emoji: '👓' },
      { id: 'r61', name: 'Flavor Flav', sub: 'Public Enemy', emoji: '⏰' },
      { id: 'r62', name: 'Schoolly D', sub: 'Jive Records', emoji: '🎓' },
      { id: 'r63', name: 'Mos Def', sub: 'Rawkus Records', emoji: '🌍' },
      { id: 'r64', name: 'Talib Kweli', sub: 'Rawkus Records', emoji: '📚' },
      { id: 'r65', name: 'Black Thought', sub: 'The Roots', emoji: '🌱' },
      { id: 'r66', name: 'Q-Tip', sub: 'A Tribe Called Quest', emoji: '💡' },
      { id: 'r67', name: 'Phife Dawg', sub: 'A Tribe Called Quest', emoji: '🐾' },
      { id: 'r68', name: 'Cormega', sub: 'Legal Hustle', emoji: '⚖️' },
      { id: 'r69', name: 'Prodigy', sub: 'Mobb Deep', emoji: '🏚️' },
      { id: 'r70', name: 'Havoc', sub: 'Mobb Deep', emoji: '💣' },
      { id: 'r71', name: 'AZ', sub: 'EMI Records', emoji: '🗽' },
      { id: 'r72', name: 'Lupe Fiasco', sub: 'Atlantic Records', emoji: '🛹' },
      { id: 'r73', name: 'The Game', sub: 'Black Wall Street', emoji: '♟️' },
      { id: 'r74', name: 'Pusha T', sub: 'GOOD Music', emoji: '👑' },
      { id: 'r75', name: 'Nipsey Hussle', sub: 'All Money In', emoji: '🏆' },
      { id: 'r76', name: "Royce da 5'9", sub: 'PRhyme', emoji: '🥊' },
      { id: 'r77', name: '2 Chainz', sub: 'Def Jam Records', emoji: '⛓️' },
      { id: 'r78', name: 'Wale', sub: 'Maybach Music', emoji: '🦁' },
      { id: 'r79', name: 'Big KRIT', sub: 'Multi Alumni', emoji: '🌾' },
      { id: 'r80', name: 'MF DOOM', sub: 'Metal Face Records', emoji: '🎭' },
      { id: 'r81', name: 'Freddie Gibbs', sub: 'ESGN', emoji: '🎯' },
      { id: 'r82', name: 'Mac Miller', sub: 'Warner Records', emoji: '🎸' },
      { id: 'r83', name: 'Chance the Rapper', sub: 'Independent', emoji: '🎪' },
      { id: 'r84', name: 'Childish Gambino', sub: 'Glassnote Records', emoji: '🎭' },
      { id: 'r85', name: 'ScHoolboy Q', sub: 'Top Dawg Entertainment', emoji: '🎓' },
      { id: 'r86', name: 'Ab-Soul', sub: 'Top Dawg Entertainment', emoji: '🧿' },
      { id: 'r87', name: 'Earl Sweatshirt', sub: 'Odd Future', emoji: '🌀' },
      { id: 'r88', name: "Joey Bada$$", sub: 'Pro Era', emoji: '🌙' },
      { id: 'r89', name: 'Vince Staples', sub: 'Blacksmith Records', emoji: '🌊' },
      { id: 'r90', name: 'Nicki Minaj', sub: 'Young Money', emoji: '👸' },
      { id: 'r91', name: 'Megan Thee Stallion', sub: '300 Entertainment', emoji: '🐴' },
      { id: 'r92', name: 'Lil Baby', sub: 'Quality Control', emoji: '👶' },
      { id: 'r93', name: 'Lil Durk', sub: 'Only the Family', emoji: '🦅' },
      { id: 'r94', name: 'Polo G', sub: 'Columbia Records', emoji: '🕊️' },
      { id: 'r95', name: 'Rod Wave', sub: 'Alamo Records', emoji: '🌊' },
      { id: 'r96', name: 'Gunna', sub: 'Young Stoner Life', emoji: '🔫' },
      { id: 'r97', name: 'Travis Scott', sub: 'Cactus Jack', emoji: '🌵' },
      { id: 'r98', name: 'Cardi B', sub: 'Atlantic Records', emoji: '💅' },
      { id: 'r99', name: 'NBA YoungBoy', sub: 'Atlantic Records', emoji: '👑' },
      { id: 'r100', name: 'Ice-T', sub: 'Sire Records', emoji: '🧊' },
      { id: 'r101', name: 'Raekwon', sub: 'Wu-Tang Clan', emoji: '🍳' },
    ]
  },
  {
    id: 'albums',
    label: 'Albums',
    title: 'Greatest Album',
    subtitle: 'Of All Time',
    emoji: '💿',
    contestants: [
      { id: 'a1', name: 'Thriller', sub: 'Michael Jackson (1982)', emoji: '🌙' },
      { id: 'a2', name: 'The Dark Side of the Moon', sub: 'Pink Floyd (1973)', emoji: '🌈' },
      { id: 'a3', name: 'Illmatic', sub: 'Nas (1994)', emoji: '🎧' },
      { id: 'a4', name: 'Ready to Die', sub: 'Biggie Smalls (1994)', emoji: '🔫' },
      { id: 'a5', name: 'Purple Rain', sub: 'Prince (1984)', emoji: '🟣' },
      { id: 'a6', name: 'Nevermind', sub: 'Nirvana (1991)', emoji: '🎸' },
      { id: 'a7', name: "What's Going On", sub: 'Marvin Gaye (1971)', emoji: '🕊️' },
      { id: 'a8', name: 'The Blueprint', sub: 'Jay-Z (2001)', emoji: '📋' },
      { id: 'a9', name: 'Abbey Road', sub: 'The Beatles (1969)', emoji: '🚶' },
      { id: 'a10', name: 'Rumours', sub: 'Fleetwood Mac (1977)', emoji: '🌬️' },
      { id: 'a11', name: 'Led Zeppelin IV', sub: 'Led Zeppelin (1971)', emoji: '🪄' },
      { id: 'a12', name: 'Born to Run', sub: 'Bruce Springsteen (1975)', emoji: '🏃' },
      { id: 'a13', name: 'Kind of Blue', sub: 'Miles Davis (1959)', emoji: '🎺' },
      { id: 'a14', name: 'Songs in the Key of Life', sub: 'Stevie Wonder (1976)', emoji: '🎹' },
      { id: 'a15', name: 'Exile on Main St.', sub: 'Rolling Stones (1972)', emoji: '👅' },
      { id: 'a16', name: 'Blonde on Blonde', sub: 'Bob Dylan (1966)', emoji: '🎶' },
      { id: 'a17', name: 'Pet Sounds', sub: 'The Beach Boys (1966)', emoji: '🌊' },
      { id: 'a18', name: 'The Miseducation of Lauryn Hill', sub: 'Lauryn Hill (1998)', emoji: '📚' },
      { id: 'a19', name: 'To Pimp a Butterfly', sub: 'Kendrick Lamar (2015)', emoji: '🦋' },
      { id: 'a20', name: 'DAMN.', sub: 'Kendrick Lamar (2017)', emoji: '🎯' },
      { id: 'a21', name: 'Goodbye Yellow Brick Road', sub: 'Elton John (1973)', emoji: '🌈' },
      { id: 'a22', name: 'Tapestry', sub: 'Carole King (1971)', emoji: '🧶' },
      { id: 'a23', name: 'The Joshua Tree', sub: 'U2 (1987)', emoji: '🌵' },
      { id: 'a24', name: 'Appetite for Destruction', sub: "Guns N' Roses (1987)", emoji: '💥' },
      { id: 'a25', name: 'Back in Black', sub: 'AC/DC (1980)', emoji: '⚡' },
      { id: 'a26', name: 'Hotel California', sub: 'Eagles (1977)', emoji: '🏨' },
      { id: 'a27', name: 'Achtung Baby', sub: 'U2 (1991)', emoji: '👶' },
      { id: 'a28', name: 'OK Computer', sub: 'Radiohead (1997)', emoji: '💻' },
      { id: 'a29', name: 'Random Access Memories', sub: 'Daft Punk (2013)', emoji: '🤖' },
      { id: 'a30', name: '21', sub: 'Adele (2011)', emoji: '💔' },
      { id: 'a31', name: 'Lemonade', sub: 'Beyoncé (2016)', emoji: '🍋' },
      { id: 'a32', name: '1989', sub: 'Taylor Swift (2014)', emoji: '🎀' },
      { id: 'a33', name: 'Folklore', sub: 'Taylor Swift (2020)', emoji: '🌲' },
      { id: 'a34', name: 'My Beautiful Dark Twisted Fantasy', sub: 'Kanye West (2010)', emoji: '🎨' },
      { id: 'a35', name: 'The College Dropout', sub: 'Kanye West (2004)', emoji: '🎓' },
      { id: 'a36', name: 'All Eyez on Me', sub: 'Tupac Shakur (1996)', emoji: '👁️' },
      { id: 'a37', name: 'Doggystyle', sub: 'Snoop Dogg (1993)', emoji: '🐕' },
      { id: 'a38', name: 'The Chronic', sub: 'Dr. Dre (1992)', emoji: '💨' },
      { id: 'a39', name: 'Straight Outta Compton', sub: 'NWA (1988)', emoji: '🎤' },
      { id: 'a40', name: 'Enter the Wu-Tang (36 Chambers)', sub: 'Wu-Tang Clan (1993)', emoji: '🐉' },
      { id: 'a41', name: 'Reasonable Doubt', sub: 'Jay-Z (1996)', emoji: '⚖️' },
      { id: 'a42', name: 'ATLiens', sub: 'OutKast (1996)', emoji: '👽' },
      { id: 'a43', name: 'Speakerboxxx/The Love Below', sub: 'OutKast (2003)', emoji: '📢' },
      { id: 'a44', name: 'Graduation', sub: 'Kanye West (2007)', emoji: '🎓' },
      { id: 'a45', name: 'Late Registration', sub: 'Kanye West (2005)', emoji: '📝' },
      { id: 'a46', name: 'Me Against the World', sub: 'Tupac Shakur (1995)', emoji: '🌍' },
      { id: 'a47', name: 'Bat Out of Hell', sub: 'Meat Loaf (1977)', emoji: '🦇' },
      { id: 'a48', name: 'Kid A', sub: 'Radiohead (2000)', emoji: '👦' },
      { id: 'a49', name: 'Born This Way', sub: 'Lady Gaga (2011)', emoji: '🌈' },
      { id: 'a50', name: 'Ctrl', sub: 'SZA (2017)', emoji: '🌸' },
    ]
  },
  {
    id: 'presidents',
    label: 'Presidents',
    title: 'Greatest President',
    subtitle: 'Of All Time',
    emoji: '🦅',
    contestants: [
      { id: 'p1', name: 'Abraham Lincoln', sub: '16th President (1861-1865)', emoji: '🎩' },
      { id: 'p2', name: 'George Washington', sub: '1st President (1789-1797)', emoji: '🦅' },
      { id: 'p3', name: 'Franklin D. Roosevelt', sub: '32nd President (1933-1945)', emoji: '🗽' },
      { id: 'p4', name: 'Theodore Roosevelt', sub: '26th President (1901-1909)', emoji: '🐻' },
      { id: 'p5', name: 'Thomas Jefferson', sub: '3rd President (1801-1809)', emoji: '📜' },
      { id: 'p6', name: 'John F. Kennedy', sub: '35th President (1961-1963)', emoji: '🌟' },
      { id: 'p7', name: 'Harry S. Truman', sub: '33rd President (1945-1953)', emoji: '☮️' },
      { id: 'p8', name: 'Dwight D. Eisenhower', sub: '34th President (1953-1961)', emoji: '⭐' },
      { id: 'p9', name: 'James K. Polk', sub: '11th President (1845-1849)', emoji: '🗺️' },
      { id: 'p10', name: 'James Monroe', sub: '5th President (1817-1825)', emoji: '🌎' },
      { id: 'p11', name: 'Andrew Jackson', sub: '7th President (1829-1837)', emoji: '💰' },
      { id: 'p12', name: 'Woodrow Wilson', sub: '28th President (1913-1921)', emoji: '🕊️' },
      { id: 'p13', name: 'Barack Obama', sub: '44th President (2009-2017)', emoji: '✨' },
      { id: 'p14', name: 'Ronald Reagan', sub: '40th President (1981-1989)', emoji: '🇺🇸' },
      { id: 'p15', name: 'Lyndon B. Johnson', sub: '36th President (1963-1969)', emoji: '🌾' },
      { id: 'p16', name: 'James Madison', sub: '4th President (1809-1817)', emoji: '📖' },
      { id: 'p17', name: 'John Adams', sub: '2nd President (1797-1801)', emoji: '⚖️' },
      { id: 'p18', name: 'Calvin Coolidge', sub: '30th President (1923-1929)', emoji: '🏛️' },
      { id: 'p19', name: 'Grover Cleveland', sub: '22nd & 24th President', emoji: '🔁' },
      { id: 'p20', name: 'William McKinley', sub: '25th President (1897-1901)', emoji: '🌺' },
      { id: 'p21', name: 'Ulysses S. Grant', sub: '18th President (1869-1877)', emoji: '⚔️' },
      { id: 'p22', name: 'Benjamin Harrison', sub: '23rd President (1889-1893)', emoji: '🌲' },
      { id: 'p23', name: 'Martin Van Buren', sub: '8th President (1837-1841)', emoji: '🌷' },
      { id: 'p24', name: 'John Tyler', sub: '10th President (1841-1845)', emoji: '🏠' },
      { id: 'p25', name: 'William Henry Harrison', sub: '9th President (1841)', emoji: '🤧' },
      { id: 'p26', name: 'Millard Fillmore', sub: '13th President (1850-1853)', emoji: '🕯️' },
      { id: 'p27', name: 'Franklin Pierce', sub: '14th President (1853-1857)', emoji: '🌧️' },
      { id: 'p28', name: 'James Buchanan', sub: '15th President (1857-1861)', emoji: '🪑' },
      { id: 'p29', name: 'Andrew Johnson', sub: '17th President (1865-1869)', emoji: '🔨' },
      { id: 'p30', name: 'Warren G. Harding', sub: '29th President (1921-1923)', emoji: '📰' },
      { id: 'p31', name: 'Herbert Hoover', sub: '31st President (1929-1933)', emoji: '📉' },
      { id: 'p32', name: 'Richard Nixon', sub: '37th President (1969-1974)', emoji: '✌️' },
      { id: 'p33', name: 'Gerald Ford', sub: '38th President (1974-1977)', emoji: '⛳' },
      { id: 'p34', name: 'Jimmy Carter', sub: '39th President (1977-1981)', emoji: '🥜' },
      { id: 'p35', name: 'Bill Clinton', sub: '42nd President (1993-2001)', emoji: '🎷' },
      { id: 'p36', name: 'George H.W. Bush', sub: '41st President (1989-1993)', emoji: '🪂' },
      { id: 'p37', name: 'George W. Bush', sub: '43rd President (2001-2009)', emoji: '🤠' },
      { id: 'p38', name: 'Donald Trump', sub: '45th & 47th President', emoji: '🏌️' },
      { id: 'p39', name: 'Joe Biden', sub: '46th President (2021-2025)', emoji: '🕶️' },
      { id: 'p40', name: 'Chester A. Arthur', sub: '21st President (1881-1885)', emoji: '👔' },
      { id: 'p41', name: 'Rutherford B. Hayes', sub: '19th President (1877-1881)', emoji: '🏛️' },
      { id: 'p42', name: 'James A. Garfield', sub: '20th President (1881)', emoji: '📚' },
      { id: 'p43', name: 'William Howard Taft', sub: '27th President (1909-1913)', emoji: '⚖️' },
      { id: 'p44', name: 'James Monroe', sub: '5th President', emoji: '🌎' },
    ]
  },
  {
    id: 'nba',
    label: 'NBA Players',
    title: 'Greatest NBA Player',
    subtitle: 'Of All Time',
    emoji: '🏀',
    contestants: [
      { id: 'n1', name: 'Michael Jordan', sub: 'Chicago Bulls', emoji: '🐐' },
      { id: 'n2', name: 'LeBron James', sub: 'Multiple Teams', emoji: '👑' },
      { id: 'n3', name: 'Kareem Abdul-Jabbar', sub: 'Lakers / Bucks', emoji: '🏀' },
      { id: 'n4', name: 'Magic Johnson', sub: 'Los Angeles Lakers', emoji: '🪄' },
      { id: 'n5', name: 'Larry Bird', sub: 'Boston Celtics', emoji: '🍀' },
      { id: 'n6', name: 'Wilt Chamberlain', sub: 'Multiple Teams', emoji: '🏛️' },
      { id: 'n7', name: 'Bill Russell', sub: 'Boston Celtics', emoji: '☘️' },
      { id: 'n8', name: 'Kobe Bryant', sub: 'Los Angeles Lakers', emoji: '🐍' },
      { id: 'n9', name: "Shaquille O'Neal", sub: 'Multiple Teams', emoji: '💪' },
      { id: 'n10', name: 'Tim Duncan', sub: 'San Antonio Spurs', emoji: '🏗️' },
      { id: 'n11', name: 'Oscar Robertson', sub: 'Bucks / Royals', emoji: '🎯' },
      { id: 'n12', name: 'Hakeem Olajuwon', sub: 'Houston Rockets', emoji: '🌊' },
      { id: 'n13', name: 'Julius Erving', sub: '76ers / Nets', emoji: '✈️' },
      { id: 'n14', name: 'Charles Barkley', sub: 'Multiple Teams', emoji: '🐖' },
      { id: 'n15', name: 'John Stockton', sub: 'Utah Jazz', emoji: '🎸' },
      { id: 'n16', name: 'Karl Malone', sub: 'Utah Jazz', emoji: '🚜' },
      { id: 'n17', name: 'Jerry West', sub: 'Los Angeles Lakers', emoji: '🎯' },
      { id: 'n18', name: 'Elgin Baylor', sub: 'Los Angeles Lakers', emoji: '⭐' },
      { id: 'n19', name: 'Moses Malone', sub: 'Multiple Teams', emoji: '💪' },
      { id: 'n20', name: 'Bob Pettit', sub: 'St. Louis Hawks', emoji: '🦅' },
      { id: 'n21', name: 'Rick Barry', sub: 'Golden State Warriors', emoji: '🏹' },
      { id: 'n22', name: 'Pete Maravich', sub: 'Multiple Teams', emoji: '🎪' },
      { id: 'n23', name: 'Isiah Thomas', sub: 'Detroit Pistons', emoji: '⚡' },
      { id: 'n24', name: 'Patrick Ewing', sub: 'New York Knicks', emoji: '🗽' },
      { id: 'n25', name: 'Dominique Wilkins', sub: 'Atlanta Hawks', emoji: '🦅' },
      { id: 'n26', name: 'Clyde Drexler', sub: 'Portland Trail Blazers', emoji: '🌹' },
      { id: 'n27', name: 'Gary Payton', sub: 'Seattle SuperSonics', emoji: '🧤' },
      { id: 'n28', name: 'Dennis Rodman', sub: 'Multiple Teams', emoji: '🎨' },
      { id: 'n29', name: 'Scottie Pippen', sub: 'Chicago Bulls', emoji: '🐂' },
      { id: 'n30', name: 'Kevin Garnett', sub: 'Multiple Teams', emoji: '💚' },
      { id: 'n31', name: 'Allen Iverson', sub: 'Philadelphia 76ers', emoji: '🔥' },
      { id: 'n32', name: 'Steve Nash', sub: 'Phoenix Suns', emoji: '☀️' },
      { id: 'n33', name: 'Dirk Nowitzki', sub: 'Dallas Mavericks', emoji: '🤠' },
      { id: 'n34', name: 'Dwyane Wade', sub: 'Miami Heat', emoji: '🌊' },
      { id: 'n35', name: 'Chris Paul', sub: 'Multiple Teams', emoji: '🎩' },
      { id: 'n36', name: 'Kevin Durant', sub: 'Multiple Teams', emoji: '🌧️' },
      { id: 'n37', name: 'Stephen Curry', sub: 'Golden State Warriors', emoji: '🏹' },
      { id: 'n38', name: 'Giannis Antetokounmpo', sub: 'Milwaukee Bucks', emoji: '🦌' },
      { id: 'n39', name: 'Nikola Jokic', sub: 'Denver Nuggets', emoji: '🥩' },
      { id: 'n40', name: 'James Harden', sub: 'Multiple Teams', emoji: '🧔' },
      { id: 'n41', name: 'Russell Westbrook', sub: 'Multiple Teams', emoji: '💨' },
      { id: 'n42', name: 'Paul Pierce', sub: 'Boston Celtics', emoji: '💚' },
      { id: 'n43', name: 'Reggie Miller', sub: 'Indiana Pacers', emoji: '⏱️' },
      { id: 'n44', name: 'Ray Allen', sub: 'Multiple Teams', emoji: '🎯' },
      { id: 'n45', name: 'Tracy McGrady', sub: 'Multiple Teams', emoji: '😴' },
      { id: 'n46', name: 'Vince Carter', sub: 'Multiple Teams', emoji: '🚀' },
      { id: 'n47', name: 'David Robinson', sub: 'San Antonio Spurs', emoji: '⚓' },
      { id: 'n48', name: 'Bob Cousy', sub: 'Boston Celtics', emoji: '🎩' },
      { id: 'n49', name: 'Pau Gasol', sub: 'Multiple Teams', emoji: '🌹' },
      { id: 'n50', name: 'Dave Cowens', sub: 'Boston Celtics', emoji: '🍀' },
    ]
  }
]

export function eloUpdate(scores, winIdx, loseIdx) {
  const K = 32
  const expected = 1 / (1 + Math.pow(10, (scores[loseIdx] - scores[winIdx]) / 400))
  const newScores = [...scores]
  newScores[winIdx] = Math.round(scores[winIdx] + K * (1 - expected))
  newScores[loseIdx] = Math.round(scores[loseIdx] + K * (0 - (1 - expected)))
  return newScores
}

export function getRandomPair(n) {
  let a = Math.floor(Math.random() * n)
  let b = Math.floor(Math.random() * n)
  while (b === a) b = Math.floor(Math.random() * n)
  return [a, b]
}
