export const categories = [
  {
    id: 'disney',
    label: 'Disney Rides',
    title: 'Greatest Disney Ride',
    subtitle: 'Walt Disney World, Orlando',
    emoji: '🏰',
    contestants: [
      { id: 'd1', name: 'Avatar: Flight of Passage', sub: 'Animal Kingdom', emoji: '🌿' },
      { id: 'd2', name: 'Rise of the Resistance', sub: 'Hollywood Studios', emoji: '⚡' },
      { id: 'd3', name: 'Haunted Mansion', sub: 'Magic Kingdom', emoji: '👻' },
      { id: 'd4', name: 'Space Mountain', sub: 'Magic Kingdom', emoji: '🚀' },
      { id: 'd5', name: 'Pirates of the Caribbean', sub: 'Magic Kingdom', emoji: '☠️' },
      { id: 'd6', name: 'Tower of Terror', sub: 'Hollywood Studios', emoji: '🏨' },
      { id: 'd7', name: 'Expedition Everest', sub: 'Animal Kingdom', emoji: '🏔️' },
      { id: 'd8', name: "Tiana's Bayou Adventure", sub: 'Magic Kingdom', emoji: '🐸' },
      { id: 'd9', name: 'Big Thunder Mountain', sub: 'Magic Kingdom', emoji: '🤠' },
      { id: 'd10', name: 'Seven Dwarfs Mine Train', sub: 'Magic Kingdom', emoji: '⛏️' },
      { id: 'd11', name: 'Tron Lightcycle Run', sub: 'Magic Kingdom', emoji: '🔵' },
      { id: 'd12', name: 'Guardians of the Galaxy', sub: 'EPCOT', emoji: '🌌' },
      { id: 'd13', name: "Remy's Ratatouille Adventure", sub: 'EPCOT', emoji: '🐭' },
      { id: 'd14', name: 'Frozen Ever After', sub: 'EPCOT', emoji: '❄️' },
      { id: 'd15', name: 'Test Track', sub: 'EPCOT', emoji: '🏎️' },
      { id: 'd16', name: "Soarin' Around the World", sub: 'EPCOT', emoji: '🌍' },
      { id: 'd17', name: 'Mission: Space', sub: 'EPCOT', emoji: '🛸' },
      { id: 'd18', name: 'Spaceship Earth', sub: 'EPCOT', emoji: '🌐' },
      { id: 'd19', name: 'Kilimanjaro Safaris', sub: 'Animal Kingdom', emoji: '🦁' },
      { id: 'd20', name: 'DINOSAUR', sub: 'Animal Kingdom', emoji: '🦕' },
      { id: 'd21', name: "Na'vi River Journey", sub: 'Animal Kingdom', emoji: '🌺' },
      { id: 'd22', name: 'Kali River Rapids', sub: 'Animal Kingdom', emoji: '🌊' },
      { id: 'd23', name: 'Slinky Dog Dash', sub: 'Hollywood Studios', emoji: '🐕' },
      { id: 'd24', name: 'Millennium Falcon: Smugglers Run', sub: 'Hollywood Studios', emoji: '🚀' },
      { id: 'd25', name: "Rock 'n' Roller Coaster", sub: 'Hollywood Studios', emoji: '🎸' },
      { id: 'd26', name: "Mickey & Minnie's Runaway Railway", sub: 'Hollywood Studios', emoji: '🐭' },
      { id: 'd27', name: 'Toy Story Mania', sub: 'Hollywood Studios', emoji: '🎯' },
      { id: 'd28', name: 'Star Tours', sub: 'Hollywood Studios', emoji: '⭐' },
      { id: 'd29', name: "Muppet*Vision 3D", sub: 'Hollywood Studios', emoji: '🐸' },
      { id: 'd30', name: 'Liberty Square Riverboat', sub: 'Magic Kingdom', emoji: '⛵' },
      { id: 'd31', name: 'Dumbo the Flying Elephant', sub: 'Magic Kingdom', emoji: '🐘' },
      { id: 'd32', name: "Peter Pan's Flight", sub: 'Magic Kingdom', emoji: '🧚' },
      { id: 'd33', name: "It's a Small World", sub: 'Magic Kingdom', emoji: '🌏' },
      { id: 'd34', name: 'The Barnstormer', sub: 'Magic Kingdom', emoji: '✈️' },
      { id: 'd35', name: 'Tomorrowland Speedway', sub: 'Magic Kingdom', emoji: '🏁' },
      { id: 'd36', name: "Buzz Lightyear's Space Ranger Spin", sub: 'Magic Kingdom', emoji: '🤖' },
      { id: 'd37', name: 'Under the Sea - Journey of the Little Mermaid', sub: 'Magic Kingdom', emoji: '🧜' },
      { id: 'd38', name: 'The Magic Carpets of Aladdin', sub: 'Magic Kingdom', emoji: '🪄' },
      { id: 'd39', name: 'Jungle Cruise', sub: 'Magic Kingdom', emoji: '🐊' },
      { id: 'd40', name: 'Walt Disney World Railroad', sub: 'Magic Kingdom', emoji: '🚂' },
      { id: 'd41', name: 'Journey Into Imagination with Figment', sub: 'EPCOT', emoji: '🎨' },
      { id: 'd42', name: 'Living with the Land', sub: 'EPCOT', emoji: '🌱' },
      { id: 'd43', name: 'Prince Charming Regal Carrousel', sub: 'Magic Kingdom', emoji: '🎠' },
      { id: 'd44', name: 'Indiana Jones Epic Stunt Spectacular', sub: 'Hollywood Studios', emoji: '🎬' },
    ]
  },
  {
    id: 'rappers',
    label: 'Rappers',
    title: 'Greatest Rapper',
    subtitle: 'Of All Time',
    emoji: '🎤',
    contestants: [
      { id: 'r1', name: 'Tupac Shakur', sub: 'Death Row Records', emoji: '👑' },
      { id: 'r2', name: 'Biggie Smalls', sub: 'Bad Boy Records', emoji: '🎤' },
      { id: 'r3', name: 'Jay-Z', sub: 'Roc-A-Fella Records', emoji: '💎' },
      { id: 'r4', name: 'Eminem', sub: 'Aftermath Entertainment', emoji: '🎵' },
      { id: 'r5', name: 'Kendrick Lamar', sub: 'pgLang / TDE', emoji: '🏆' },
      { id: 'r6', name: 'Nas', sub: 'Columbia Records', emoji: '🔥' },
      { id: 'r7', name: 'Lil Wayne', sub: 'Cash Money Records', emoji: '🐉' },
      { id: 'r8', name: 'Drake', sub: 'OVO Sound', emoji: '🦉' },
      { id: 'r9', name: 'Rakim', sub: 'Eric B. & Rakim', emoji: '🎙️' },
      { id: 'r10', name: 'Andre 3000', sub: 'OutKast', emoji: '🪐' },
      { id: 'r11', name: 'Ice Cube', sub: 'NWA / Solo', emoji: '
